#ifdef APP_UI_WINDOWING_SYSTEM

	#define APP_UI_CPP_STRINGIFY_TOKEN_IMPL(token) #token
	#define APP_UI_CPP_STRINGIFY_TOKEN(token) APP_UI_CPP_STRINGIFY_TOKEN_IMPL(token)

	#include APP_UI_CPP_STRINGIFY_TOKEN(ui.cpp.APP_UI_WINDOWING_SYSTEM.impl)

	#undef APP_UI_CPP_STRINGIFY_TOKEN
	#undef APP_UI_CPP_STRINGIFY_TOKEN_IMPL

#else

	#error "APP_UI_WINDOWING_SYSTEM is not defined."

#endif
